[package]

name = "gfx-debug-draw"
version = "0.0.1"
authors = ["Steve Jahns <s.t.jahns@gmail.com>"]

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.gfx_macros]
git = "https://github.com/gfx-rs/gfx-rs"
